#ifndef VERSION_H
#define VERSION_H

#define VERSION_1 0
#define VERSION_2 0
#define VERSION_3 0
#define VERSION_4 1
#define COMM_SINGLETON_VERSION_1 0
#define COMM_SINGLETON_VERSION_2 0
#define COMM_SINGLETON_VERSION_3 0
#define COMM_WRAPPER_VERSION_1 0
#define COMM_WRAPPER_VERSION_2 0
#define COMM_WRAPPER_VERSION_3 3

#endif // VERSION_H
